= Diet Points Runner

- Demo of a scoring algorithm for the dietary value of food sold by a grocery store

        ◦ Based on the keywords, the nutrients should be grouped as elements and points should be awarded.
        ◦ Point Rules
            ▪ If the item has 3 nutrients out of listed nutrients below with %dv greater than 10, award 3 points to element Nutrient Density
            ▪ If the item has 2 nutrients out of listed nutrients below with %dv greater than 10, award 2 points to element Nutrient Density
            ▪ If the item has 3 nutrients out of listed nutrients below with %dv greater than 5, award 2 points to element Nutrient Density
            ▪ If the item doesn’t have any nutrients listed below, award 0 points.
                • Nutrients (key words):
                    ◦ Biotin
                    ◦ Calcium
                    ◦ Chromium

        ◦ Add a new element EPA DHA
        ◦ Point rules
            ▪ If the total (summed up) quantity of the following nutrients of an item greater than 12.5 mg and has at least 2 of the following ingredients then award 2 points. 
                • Nutrients (key word)
                    ◦ EPA
                    ◦ DHA
                • Ingredients (key word)
                    ◦ Wheat
                    ◦ Whole oat
                    ◦ Wheat berries

        ◦ Add an element added sugar
        ◦ Point rules
            ▪ If the item has the nutrient Added Sugars and one of the following ingredient keywords, then calculate the %kcal as follows. 
					Total Quantity %KCAL = 4 * Nutrient quantity * 100 / Total calories
                • Ingredients (key words)
                    ◦ Agave
                    ◦ Sweetener
                    ◦ Cane Sugar
            ▪ If the total quantity %kcal is greater than 10, then award -2 points to element Added sugars
            ▪ If the total quantity %kcal is greater than 5, then award -1 points to element Added sugars
        ◦ Star rules
            ▪ If the total points for all the elements are greater than or equal to 10, then award 3 stars to the item. 
            ▪ If the total points for all the elements are greater than or equal to 5, then award 2 stars to the item. 

        ◦ Star rules
            ▪ If the total points for all the elements are greater than or equal to 10, then award 3 stars to the item. 
            ▪ If the total points for all the elements are greater than or equal to 5, then award 2 stars to the item. 


- execute by running

[source,java]
---
mvn -e exec:java -Dexec.mainClass="com.telecom.Calculate"
---