package com.telecom;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Issue implements Serializable {

	static final long serialVersionUID = 1L;
	
	private Integer issueId;

	private Long serverSerial;

	private String neName;

	private String summary;

	private Long timeOfIncident;

	private Long acServerSerial;

	private Long timeAcBackUp;

	public Issue() {
	}
	
	public Integer getIssueId() {
	    return this.issueId;
	}
	
	public void setIssueId(Integer issueId) {
	    this.issueId = issueId;
	}

	public Long getServerSerial() {
		return this.serverSerial;
	}

	public void setServerSerial(Long serverSerial) {
		this.serverSerial = serverSerial;
	}

	public java.lang.String getNeName() {
		return this.neName;
	}

	public void setNeName(String neName) {
		this.neName = neName;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public java.lang.Long getTimeOfIncident() {
		return this.timeOfIncident;
	}

	public void setTimeOfIncident(Long timeOfIncident) {
		this.timeOfIncident = timeOfIncident;
	}

	public java.lang.Long getAcServerSerial() {
		return this.acServerSerial;
	}

	public void setAcServerSerial(Long acServerSerial) {
		this.acServerSerial = acServerSerial;
	}

	public Long getTimeAcBackUp() {
		return this.timeAcBackUp;
	}

	public void setTimeAcBackUp(Long timeAcBackUp) {
		this.timeAcBackUp = timeAcBackUp;
	}

	public Issue(Integer issueId, Long serverSerial, String neName,
			String summary, Long timeOfIncident,
			Long acServerSerial, Long timeAcBackUp) {
	    this.issueId = issueId;
		this.serverSerial = serverSerial;
		this.neName = neName;
		this.summary = summary;
		this.timeOfIncident = timeOfIncident;
		this.acServerSerial = acServerSerial;
		this.timeAcBackUp = timeAcBackUp;
	}

}